"""empty message

Revision ID: 1beb273beaf4
Revises: 4db6c3aff277
Create Date: 2020-05-02 10:59:57.654362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1beb273beaf4'
down_revision = '4db6c3aff277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE student SET completed=False WhERE completed is NULL')
    op.alter_column('student','completed',nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'completed')
    # ### end Alembic commands ###
