"""empty message

Revision ID: 91c3a40157b0
Revises: 1beb273beaf4
Create Date: 2020-05-03 14:04:15.640470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c3a40157b0'
down_revision = '1beb273beaf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'todolists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'list_id')
    op.drop_table('todolists')
    # ### end Alembic commands ###
